// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/toshi/Dev/VehicleChecklist/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/toshi/Dev/VehicleChecklist/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('VehicleChecklist', appParameters);
});
require('c:/Users/toshi/Dev/VehicleChecklist/index.android.js');